spring.application.name=checkout-service
spring.datasource.url=jdbc:postgresql://postgres-db:5432/demo
spring.datasource.username=postgres
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver
